smokedetector_check:
  description: Calls test routine of Bosch Smoke Detector.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "binary_sensor.smokedetector_living_room"
